#ifndef __INC_RESPWANSETTINGS_H
#define __INC_RESPWANSETTINGS_H

#define DEFAULT_SHORT_RESPAWN_MILLIS 5000
#define DEFAULT_MEDIUM_RESPAWN_MILLIS 10000
#define DEFAULT_LONG_RESPAWN_MILLIS 20000

typedef enum {
    SPAWN_DURATION_SHORT = 0,
    SPAWN_DURATION_MEDIUM = 1,
    SPAWN_DURATION_LONG = 2,
} RespawnDurationSlot;

typedef struct {
    int BP_VERSION;
    long durations[3] = { DEFAULT_SHORT_RESPAWN_MILLIS, DEFAULT_MEDIUM_RESPAWN_MILLIS, DEFAULT_LONG_RESPAWN_MILLIS};
} RespawnSettings;

#endif